config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/trending', to: 'trending_fonts#index', as: 'trending'
  get '/popular', to: 'popular_fonts#index', as: 'popular'
  get '/recent', to: 'recent_fonts#index', as: 'recent'
  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout


  namespace :api, defaults: { format: 'json'} do
    namespace :v1 do
      namespace :fonts do
        resources :trending, only: [:index]
        resources :recent, only: [:index]
        resources :popular, only: [:index]
      end
    end
  end

  match '*any' => 'api#options', :via => [:options]
end

app/models/font.rb
class Font < OpenStruct

  def self.service
    GoogleFontService.new
  end

  def self.all(method)
    raw_fonts = service.send(method)
    ranking = 0
    raw_fonts.first(10).map do |font|
      Font.new(family: font[:family], file: font[:files][:regular],
               subsets: font[:subsets].join(', '), cdn: get_cdn_link(font),
               ranking: (ranking += 1).to_s )
    end
  end

  def self.get_cdn_link(font)
    family = font[:family]
    "https://fonts.googleapis.com/css?family=#{family.split.join("+")}"
  end

  def idify
    family.split.join("-")
  end

  def find_rank(fonts)
    fonts.index(self) + 1
  end
end

app/controllers/api/v1/fonts/popular_controller.rb
class Api::V1::Fonts::PopularController < ApplicationController
  respond_to :json

  def index
    respond_with Font.all("popular_fonts")
  end

end

app/controllers/api/v1/fonts/recent_controller.rb
class Api::V1::Fonts::RecentController < ApplicationController
  respond_to :json

  def index
    respond_with Font.all("recent_fonts")
  end

end

app/controllers/api/v1/fonts/trending_controller.rb
class Api::V1::Fonts::TrendingController < ApplicationController
  respond_to :json

  def index
    respond_with Font.all("trending_fonts")
  end

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  helper_method :current_user
  protect_from_forgery with: :null_session
  respond_to :html, :json

  def current_user
    @user ||=  OpenStruct.new(session[:user]) if session[:user]
  end

  def required_fonts
    @required_families = Font.all(params["controller"]).map do |font|
      font.family
    end.map(&:to_s).join(", ")
  end

end

app/controllers/popular_fonts_controller.rb
class PopularFontsController < ApplicationController
  before_action :required_fonts, only: [:index]

    def index
      @popular_fonts = Font.all(params['controller'])
    end

end

app/controllers/recent_fonts_controller.rb
class RecentFontsController < ApplicationController
  before_action :required_fonts, only: [:index]

  def index
    @recent_fonts = Font.all(params["controller"])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = request.env["omniauth.auth"][:info]
    session[:user] = user
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/trending_fonts_controller.rb
class TrendingFontsController < ApplicationController
  before_action :required_fonts, only: [:index]

  def index
    @trending_fonts = Font.all(params['controller'])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fonts/index.html.erb
<div class="all">
  <% @trending_fonts.each do |font| %>
  <div class= "font" style="font-family:<%= font.family%>;">
    <div class="ranking">
      <h1><%= @trending_fonts.index(font) + 1 %></h1>
    </div>
    <h2><%= font.family %></h2>
    <p><%= font.subsets %></p>
    <br>
    <div class="actions">
      <%= link_to "Download", font.file, class: 'button' %>
      <br>
    </div>
      <div class="inputs">
        <input id="<%= font.idify %>" type="url" value="<%=font.cdn%>">
        <button id="copy_btn" class="<%= font.idify %>"><i class="fa fa-clipboard"></i></button>
      </div>
      <hr>
    </div>
  <br>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>trendWolf</title>
  <link href='https://fonts.googleapis.com/css?family=Cutive+Mono' rel='stylesheet' type='text/css'>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application'  %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script>
    var fonts = '<%= @required_families %>'.split(', ')
    console.log(fonts);
    WebFontConfig = {
      google: {
        families: fonts
      }
    };
    (function(d) {
      var wf = d.createElement('script'), s = d.scripts[0];
      wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js';
      s.parentNode.insertBefore(wf, s);
    })(document);
  </script>
</head>
<body>

  <%= yield %>

</body>

</html>

app/views/popular_fonts/index.html.erb
<div class="lead">
  <h1 class=popular>Popular Fonts</h1>
  <%= link_to "See Trending", trending_path %>
  <%= link_to "See Recent", recent_path %>
  <%= link_to "Home", root_path, class: 'home' %>
</div>
<div class="all">
  <% @popular_fonts.each do |font| %>
  <div class= "font" style="font-family:<%= font.family%>;">
    <div class="ranking">
      <h1><%= font.find_rank(@popular_fonts) %></h1>
    </div>
    <h2><%= font.family %></h2>
    <p><%= font.subsets %></p>
    <br>
    <div class="actions">
      <%= link_to "Download", font.file, class: 'button' %>
      <br>
    </div>
      <div class="inputs">
        CDN: <input id="<%= font.idify %>" type="url" value="<%=font.cdn%>">
        <button id="copy_btn" class="<%= font.idify %>"><i class="fa fa-clipboard"></i></button>
      </div>
      <br>
    </div>
  <br>
  <% end %>
</div>

app/views/recent_fonts/index.html.erb
<div class="lead">
  <h1 class=popular>Recent Fonts</h1>
  <%= link_to "See Trending", trending_path %>
  <%= link_to "See Popular", popular_path %>
  <%= link_to "Home", root_path, class: 'home' %>
</div>
<div class="all">
  <% @recent_fonts.each do |font| %>
  <div class= "font" style="font-family:<%= font.family%>;">
    <div class="ranking">
      <h1><%= font.find_rank(@recent_fonts) %></h1>
    </div>
    <h2><%= font.family %></h2>
    <p><%= font.subsets %></p>
    <br>
    <div class="actions">
      <%= link_to "Download", font.file, class: 'button' %>
      <br>
    </div>
      <div class="inputs">
        CDN: <input id="<%= font.idify %>" type="url" value="<%=font.cdn%>">
        <button id="copy_btn" class="<%= font.idify %>"><i class="fa fa-clipboard"></i></button>
      </div>
      <br>
    </div>
  <br>
  <% end %>
</div>

app/views/trending_fonts/index.html.erb
<div class="lead">
  <h1>Trending Fonts</h1>
  <%= link_to "See Popular", popular_path %>
  <%= link_to "Home", root_path, class: 'home' %>
</div>
<div class="all">
  <% @trending_fonts.each do |font| %>
  <div class= "font" style="font-family:<%= font.family%>;">
    <div class="ranking">
      <h1><%= font.find_rank(@trending_fonts) %></h1>
    </div>
    <h2><%= font.family %></h2>
    <p><%= font.subsets %></p>
    <br>
    <div class="actions">
      <%= link_to "Download", font.file, class: 'button' %>
      <br>
    </div>
      <div class="inputs">
        CDN: <input id="<%= font.idify %>" type="url" value="<%=font.cdn%>">
        <button id="copy_btn" class="<%= font.idify %>"><i class="fa fa-clipboard"></i></button>
      </div>
      <br>
    </div>
  <br>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="welcome-page">
  <h1 class="headline">trendWolf</h1>
  <h2 class="sub-headline">Trending, Popular,and Most Recent Fonts From Google</h2>


  <section class="landing">
    <% if current_user %>
    <div class="welcome-name">
      <h3>Hello, <%= current_user.name %></h3>
    </div>

    <div class="log-container">
      <%= link_to "Check Out Trending Fonts", trending_path, class: 'button' %>
      <%= link_to "Check Out Popular Fonts", popular_path, class: 'button' %>
      <div class='logout'>
        <%= link_to "Check Out Recent Fonts", recent_path, class: 'button' %>
        <div class='logout'>
          <%= link_to "Logout", logout_path, method: :delete, class: "button logout" %>
        </div>
      </div>
    </div>
    <% else %>
    <div class="log-container">
      <%= link_to "Log In With Google", google_login_path, class: "button log-in"  %>
    </div>
    <% end %>
  </section>
</div>